spring:
  ai:
    dashscope:
      api-key: <qwen3-key>
      chat:
        options:
          model: qwen3-max

server:
  port: 8080

# 百度车型识别
baidu:
  car:
    api-url: https://aip.baidubce.com/rest/2.0/image-classify/v1/car
    access-token: <baidu-key>
    timeout-ms: 60000